### ISSUE TITLE
Orientation of wallpaper images is flipped

### ISSUE THREAD

**Issue by loebpaul** [cmrazek/WallSwitch#4]
Occasionally an image in my wallpaper rotation will appear flipped vertically 180 degrees. The image shows up this way on the desktop and in the Wall Switch History tab. However if you double click on the image from the History tab to load it in Windows Photo Viewer, you can see the image is displayed with the correct orientation. 
My theory is that there is a parameter in the image file that describes the proper orientation (which Windows Photo Viewer is reading and Wall Switch is not) as these are likely photos I took on an iPhone held "upside down."

![2](https://user-images.githubusercontent.com/5465651/138564921-48b5c2b5-e247-4813-a5b2-8af267e8032c.JPG)

**Comment by loebpaul** [comment]
Wall Switch 1.6.3
Windows 8.1

**Comment by cmrazek** [comment]
You're right. Looks like I wasn't looking at the exif orientation flag in the image. Should be fixed with version 1.6.4.

Unfortunately, any previously-created thumbnails will still be flipped, since those are cached in the database when the image is first loaded. If you want to correct those, you can create a new 'Theme' with the same settings, and all new thumbnails going forward will have the correct orientation.

Thanks

**Comment by loebpaul** [comment]
Amazing, thank you for your quick response!
